{% set data = load_setup_py_data() %}

package:
  name: genomekit
  version: {{ data["version"] }}

source:
  path: ../

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - appdirs
    - fmt
    - numpy >=1.18.0,<1.19.0 # oldest py3.8 build for forward compatibility
    # TODO tensorflow TPU now also supports 3.10
    - python >=3.8.0,<3.9.0  # tensorflow TPU whls from google only support 3.8
    - typing-extensions
    - zlib

  run:
    - appdirs
    - crc32c
    - google-cloud-storage
    - {{ pin_compatible('numpy') }}
    - python >=3.8.0,<3.9.0
    - typing-extensions
    - importlib-metadata
    - tqdm

build:
  number: {{ environ.get('CIRCLE_BUILD_NUM', 0) }}
  script: python -m pip install --no-deps --ignore-installed .

test:
  requires:
    - bcftools
    - pytest-cov
    - samtools >=1.15
    - tabix
    - twobitreader

about:
  doc_url: {{ data["project_urls"]["Documentation"] }}
  home: {{ data["url"] }}
  license: {{ data['license'] }}
  license_file: {{ data["license_files"] | first }}
  summary: {{ data["description"] }}

extra:
  recipe-maintainers:
    - ovesh
